### ISSUE TITLE
ImportError: No module named 'pyzed.sl'

### ISSUE THREAD

**Issue by acsignal** [stereolabs/zed-tensorflow#10]
When running object_detection_zed.py within the zed-python-api directory I get the above error. The zed-python-api directory has path .\pyzed\sl.pyx and I have successfully built and installed setup.py and I am able to import pyzed in python but not pyzed.sl. Can anybody help?

**Comment by abastie** [comment]
Hi @acsignal 

Have you tried :
```
import pyzed.sl as sl
```
Because of how the python wrapper is built, you have to do it like this.

**Comment by acsignal** [comment]
I have but I get the same error

**Comment by abastie** [comment]
Which OS are you using, Ubuntu or Windows?
Which version of the ZED SDK have you installed?
Can you tell me how exactly you built and installed the python wrapper?

**Comment by JohnieBraaf** [comment]
You can resolve this by copying the so file and reinstalling:

https://github.com/stereolabs/zed-python-api/issues/78#issuecomment-493211012

**Comment by YueqiYu** [comment]
Maybe try python3 object_detection_zed.py instead of python object_detection_zed.py

**Comment by bryanbocao** [comment]
Tried installing [SDK](https://www.stereolabs.com/developers/release/) first and then following the steps in [zed-python-api](https://github.com/stereolabs/zed-python-api/tree/master/src)?

**Comment by KastanDay** [comment]
My solution (similar to @YueqiYu) requires `sudo` and `python3`
```
sudo python3 object_detection_birds_view.py
```

IMO issue can be closed.

**Comment by bassmaji** [comment]
It depends what are you using as python editor 
If you are using pycharm community simply follow the steps below 

1. Go to the terminal within the pycharm 
2. cd ./usr/local/zed
type "ls" and search for "pyzd-xxxxx.whl" etc make sure that you have the "pyzed-xxxxx.whl" file within the directory
4. type  "pip install pyzed-xxxxx.whl" whithin the terminal 

Check the external libraries and you will be able to see pyzed and your code should work without any problem 
Please let me know if you need any further help! 

Warmest, 
Aamer
