### ISSUE TITLE
Hi, Thank you for this repo. I would like  to know how can we run the model on .svo file which is already recorded instead of live feed?

### ISSUE THREAD

**Issue by rishabh700** [stereolabs/zed-tensorflow#4]

**Comment by adujardin** [comment]
Hi,
You should be able to open an SVO file by giving the SVO file path as an argument, like this :
```bash
python3 object_detection_zed.py path/to/mysvo.svo
```

You could also hardcode the path [here](https://github.com/stereolabs/zed-tensorflow/blob/5b91c59482794f53d1d88e5877b0e1a3e83c098f/object_detection_zed.py#L68) for testing purposes :
 https://github.com/stereolabs/zed-tensorflow/blob/5b91c59482794f53d1d88e5877b0e1a3e83c098f/object_detection_zed.py#L68

**Comment by rishabh700** [comment]
Great! Thank you for helping.
