### ISSUE TITLE
How to install cudnn on jetson nano

### ISSUE THREAD

**Issue by razackkpa** [stereolabs/zed-tensorflow#6]
I am trying to run 

https://github.com/stereolabs/zed-tensorflow/tree/5b91c59482794f53d1d88e5877b0e1a3e83c098f

On jetson nano

downloaded tf_gpu-1.13.1+nv19.5-py3
from
https://developer.nvidia.com/embedded/downloads#?search=Tensorflow

tried to install on jetson nano. failed.

Looks like cuDNN is not installed.  please guide me how to install

**Comment by adujardin** [comment]
On jetson cuDNN (like CUDA) is installed by the jetpack. If it wasn't enabled during the setup you may have to reflash your nano.

**Comment by etdecode** [comment]
How to manually install it as a backup solution?
---
Login then
https://developer.nvidia.com/rdp/cudnn-download
Only for x86-64

But there is no package outside of Jetpack, which forces you to reflash your SD

EDIT:

some deb package for ARM64 here
https://developer.nvidia.com/cuda-toolkit/arm
[extra instructions](https://gist.github.com/jetsonhacks/5257f2352d444c2f3240)
[official instructions](https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#installlinux)

**Comment by laserrapt0r** [comment]
sudo apt-get install libcudnn8 libcudnn8-dev libcudnn8-doc -y
