### ISSUE TITLE
Distance calculation and point cloud data

### ISSUE THREAD

**Issue by rishabh700** [stereolabs/zed-tensorflow#7]
Hi, I am unable to understand why are you calculating the distance as the square root of x,y,z in line [#L145](https://github.com/stereolabs/zed-tensorflow/blob/5b91c59482794f53d1d88e5877b0e1a3e83c098f/object_detection_zed.py#L145)? Does the z values not represent the distance of the object from the zed camera directly? If not, then it just represents the z-coordinate value similar to x and y? 

Also, does the point cloud data in `point_cloud.get_value(i,j)` where (i,j) is the pixel coordinates gives the same output as x,y,z used in this program in line [#L141](https://github.com/stereolabs/zed-tensorflow/blob/5b91c59482794f53d1d88e5877b0e1a3e83c098f/object_detection_zed.py#L141), [#L142](https://github.com/stereolabs/zed-tensorflow/blob/5b91c59482794f53d1d88e5877b0e1a3e83c098f/object_detection_zed.py#L142), [#L143](https://github.com/stereolabs/zed-tensorflow/blob/5b91c59482794f53d1d88e5877b0e1a3e83c098f/object_detection_zed.py#L143)?

**Comment by obraun-sl** [comment]
Hi,
The Z axis value represents the distance between the point and the plane Z=0 defined by the camera. 
Therefore the distance from the left sensor of the camera to the point is the euclidean distance defined by the square root of x²+y²+z².

**Comment by rishabh700** [comment]
Hi, 
Nice explanation. Thanks! The first part is clear. 
For the second part, do you also know if the point cloud's coordinated are the same as coordinates used in this code?

**Comment by obraun-sl** [comment]
Yes both methods should give the same results. Note that coordinate system (how X,Y,Z are oriented) are given by the InitParameters.coordinate_system.

**Comment by rishabh700** [comment]
Great. Thank a lot!

**Comment by ghost** [comment]
Hi,

I have a question about the coordinate system. Suppose that I detect 2 peoples and I want to compute the distance between the 2 peoples.
Can I just do a euclidian distance between center of 2 peoples, or i need to project the center of each people using intrinsec camera parameter then do euclidian distance ? 

Thanks

**Comment by rishabh700** [comment]
You can directly calculate the euclidean distance using the extracted coordinates. 
By the way, both the methods you have mentioned should give you the same result.
