### ISSUE TITLE
CUDA Context

### ISSUE THREAD

**Issue by soldierofhell** [stereolabs/zed-tensorflow#9]
Hi, could you please share some details how you manage context under the hood? In python code we can see only memory limit for Tensorflow.
By the way, is GPU mandatory for depth processing?

Regards,

**Comment by adujardin** [comment]
Hi,
The ZED SDK requires CUDA and therefore a GPU, for any tasks, including the depth computation.

The CUDA Context is by default created by the ZED SDK during the `Camera::open`. 
Using the C++ API you can provide your own with [`InitParameters::sdk_cuda_ctx`](https://www.stereolabs.com/docs/api/structsl_1_1InitParameters.html#ae684a455a5dc2e48a82b9aadc8c3ba53).

In the past, some users work around this in python with a script (see [this issue](https://github.com/stereolabs/zed-python-api/issues/35#issuecomment-401622830))

**Comment by soldierofhell** [comment]
Thank you @adujardin, in fact I already wanted to rewrite this python script to C++.
So for example by sharing context we can grab image and depth matrix/tensor directly on GPU without making copies through numpy CPU, saving GPU memory and processing time, am I right?

**Comment by adujardin** [comment]
Yes, the GPU buffers can be shared within the same CUDA Context without copying.

However, sharing the same context basically means there's no overlap possible and the computing of the ZED SDK and the inference won't be in parallel anymore. It might still be faster at the end but not necessarily. 

NB: To get parallelism while sharing a context you need to create non-blocking streams but you can't control it in the ZED SDK (it uses the default one) and I doubt you can in TensorFlow either.

**Comment by soldierofhell** [comment]
But if ZED and TF can parallelize their tasks so that all cores are used there's no benefit from overlap?
